title: Zero Log
email: anthony.zerolog@gmail.com
description: >- 

author:
  name: Anthony Joaquin Martinez

# Production url.
url: "https://zero-log.aj-martinez.com"

# Part after .com, etc. Use / if none
baseurl: ""

twitter_username: 
github_username:  Anthony-ZeroLog
timezone: America/Mexico_City

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Paginaci√≤n inicial configurada de manera global
#pagination:
#  enabled: true
#  per_page: 5
#  permalink: /page:num/
#  sort_reverse: true

#Jekyll Archives modificado
jekyll-archives:
  enabled: 
    - tags
  layout: archive
  permalinks:
    tag: /tag/:name/

# Layouts para cada categoria
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: archive
#  permalinks:
#    category: /category/:name/
#    tag: /tag/:name/

# highlighter: rouge
# markdown: kramdown
# kramdown:
#   syntax_highlighter_opts:
#      block:
#        line_numbers: true